/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zhangge_zgplayer_lib_LibZGPlayer */

#ifndef _Included_org_zhangge_zgplayer_lib_LibZGPlayer
#define _Included_org_zhangge_zgplayer_lib_LibZGPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zhangge_zgplayer_lib_LibZGPlayer
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zhangge_zgplayer_lib_LibZGPlayer_play
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
